### ISSUE TITLE
Feature/BUG SaveTextureToCameraRoll() is Not found

### ISSUE THREAD

**Issue by Storm-Develop** [StansAssets/com.stansassets.ios-native#59]
First of all the bug: **ISN_UIImagePickerController.SaveTextureToCameraRoll** is not found anymore at your code.
https://github.com/StansAssets/com.stansassets.ios-native/wiki/Save-to-Camera-Roll

And a feature needed is to pass a name to the image to be saved or taken a screenshot from. So far I couldn't see a way to do it.

**Comment by stan-osipov** [comment]
Thx for the report.
>First of all the bug: ISN_UIImagePickerController.SaveTextureToCameraRoll is not found anymore at your code.
>https://github.com/StansAssets/com.stansassets.ios-native/wiki/Save-to-Camera-Roll

Just fixed the documentation, have a look.

>And a feature needed is to pass a name to the image to be saved or taken a screenshot from. So far I couldn't see a way to >do it.

If I understood you right you would like to give a name to the image you about to save to the photo album?
Tbh I am not sure if iOS does have a feature like that, but if you will point me to the native API you are referring to I am sure it can be added to the plugin.
Thanks!

**Comment by Storm-Develop** [comment]
Hmm I couldn't find a reference in IOS docs. Seems like there's no option to do it.
```
func UIImageWriteToSavedPhotosAlbum(_ image: UIImage, 
                                  _ completionTarget: Any?, 
                                  _ completionSelector: Selector?, 
                                  _ contextInfo: UnsafeMutableRawPointer?)
```
I guess I got confused since easy mobile had that field to specify the image name.
https://www.easymobile.sglibgames.com/docs/pro/chapters/native-apis/camera-gallery/scripting.html#saving-images-into-device-gallery

**Comment by stan-osipov** [comment]
Maybe easy mobile used it as cross-platfrom API? Because you can set name on Android, and on IOS it will just be ignored.
For with Ultimate Mobile [SaveImage](https://api.stansassets.com/ultimate-mobile/SA.CrossPlatform.App.UM_iGalleryService.html#SA_CrossPlatform_App_UM_iGalleryService_SaveImage_Texture2D_System_String_Action_SA_Result__) you do have the file name option as well:


And as always if there is any native API you think plugin is missing, just give me a link and it will most likely appear in the next release :) 
Thanks.
